[MUS-61] Basic header
Drelarusoidd/React pull request #5
Opened 2022-07-12 10:47 UTC by nickkuchko

<img width="1371" alt="not Logged in" src="https://user-images.githubusercontent.com/77110489/178473216-b57dc231-2dc1-4297-9366-b415aff99a3f.png">
<img width="1371" alt="Logged in" src="https://user-images.githubusercontent.com/77110489/178473234-9244d899-481f-442d-a15b-bd032bfe1a84.png">

2022-07-12 11:04 UTC, Drelarusoidd approved these changes

2022-07-12 11:07 UTC, nickkuchko commented on src/components/navBar.js
> +        let token = localStorage.getItem('access');
Done

2022-07-19 11:55 UTC, ZubelRuslan requested changes
Before merge nav bar jsx should be refactored

2022-07-19 11:55 UTC, ZubelRuslan commented on src/components/navBar.js
> +    const [isLogin, SetIsLogin] = useState(false);
better to use traditional camelCase

2022-07-19 11:55 UTC, ZubelRuslan commented on src/components/navBar.js
> +            </Box>
A lot of code duplication

2022-07-19 11:55 UTC, ZubelRuslan commented on src/containers/AuthContainer.js
> +       window.location.reload(); // need to update navbar menu items after log in
This global state should be stored in the scope of some root element. Root element will store this data and send it to child component. In general it's a good case to use React Context or Redux

2022-07-19 11:55 UTC, ZubelRuslan commented on src/containers/LogoutContainer.js
> +            window.location.reload(); // need to update navbar menu items after logout
Same

2022-07-20 09:25 UTC, ZubelRuslan commented on src/components/navBar.js
> +            </Box>
Main mind of comments for this MR is remove this code duplication

2022-07-20 09:28 UTC, nickkuchko commented on src/components/navBar.js
> +            </Box>
I did that already, now I'm trying to figure out Context, I think I did everything, but the buttons don't update :)

2022-07-20 10:16 UTC, ZubelRuslan commented on src/components/navBar.js
> +            </Box>
@nickkuchko you can push latest changes and mention me in PR comment to check

2022-07-21 11:14 UTC, nickkuchko commented on src/components/navBar.js
> +            </Box>
@[ZubelRuslan](https://github.com/ZubelRuslan) Hi, I've just made an update using React Context

2022-07-21 22:24 UTC, ZubelRuslan requested changes

2022-07-21 22:24 UTC, ZubelRuslan commented on src/components/navBar.js
> +    }
```suggestion
        return (
            <Box sx={{ flexGrow: 1 }}>
                <AppBar position="static">
                    <Toolbar>
                        <MainNavbuttons />
                        {{ isLogin ? 
                        <Button component={Link} to="/profile" color="inherit"> {user}'s Profile </Button>
                        <Button component={Link} to="/logout" color="inherit">Logout</Button>
                        :
                        <Button component={Link} to="/login" color="inherit">Login</Button>
                        <Button component={Link} to="/register" color="inherit">Create account</Button>
                        }}
                </Toolbar>
            </AppBar>
            </Box >
        );
    }
```

2022-07-21 22:24 UTC, ZubelRuslan commented on src/components/navBar.js
> +    }
I'm already told you about duplication...

2022-07-21 22:24 UTC, ZubelRuslan commented on src/containers/AuthContainer.js
> +        }
```suggestion
   setIsLogin(!!token);
```

2022-07-22 07:32 UTC, nickkuchko commented on src/containers/AuthContainer.js
> +        }
@[ZubelRuslan](https://github.com/ZubelRuslan) Hi, I've updated requested files

2022-07-22 08:48 UTC, ZubelRuslan approved these changes

2022-07-22 08:48 UTC, ZubelRuslan commented on src/components/navBar.js
> +                    <div>
btw you can use fragment here to avoid unnecessary `div`

2022-07-22 09:03 UTC, merged