[MUS-57] music player component
Drelarusoidd/React pull request #6
Opened 2022-07-14 10:28 UTC by Drelarusoidd

2022-07-14 10:55 UTC, nickkuchko approved these changes
Everything looks good

2022-07-19 12:06 UTC, ZubelRuslan requested changes
I see a lot of copy pasted NOT REACT code. Change it!

2022-07-19 12:06 UTC, ZubelRuslan commented on src/App.css
> +}
Pls move to separate file audio player styles

2022-07-19 12:06 UTC, ZubelRuslan commented on src/components/PlayerComponent.js
> +
Looks like you can move this functions to another utils file

2022-07-19 12:06 UTC, ZubelRuslan commented on src/components/PlayerComponent.js
> +        $(`.end-time-${num.index}`).html(totalLength);
remove jquery. You can use React refs

2022-07-19 12:07 UTC, ZubelRuslan commented
> Everything looks good
m? what about player component?

2022-07-19 14:39 UTC, merged