[MUS-58] reactions component
Drelarusoidd/React pull request #7
Opened 2022-07-18 08:12 UTC by Drelarusoidd

2022-07-18 08:54 UTC, nickkuchko approved these changes
Everything looks good

2022-07-19 11:45 UTC, ZubelRuslan requested changes

2022-07-19 11:45 UTC, ZubelRuslan commented on src/components/NewsComponent.js
> +            })
Better to use `async` `await` constructions to avoid nested callbacks

2022-07-19 11:45 UTC, ZubelRuslan commented on src/components/NewsComponent.js
> +            return <span><img src={`http://127.0.0.1:8000${data?.link}`} style={{width: '200px'}} alt="cover"/><br></br><br></br></span>
Do not hardcode base urls. Pls use node environment variables

2022-07-19 11:45 UTC, ZubelRuslan commented on src/components/NewsComponent.js
> +                                }
You can call function directly from JSX `<Reactions user={user} post={post} disabled={reactions(post.user)} />`

2022-07-19 11:45 UTC, ZubelRuslan commented on src/components/NewsComponent.js
> +    const typeLink = (data, index) => {
As I see you can move this function upper from current component function because it not depends on state and other component data

2022-07-19 11:45 UTC, ZubelRuslan commented on src/components/NewsComponent.js
> +                                    : <Reactions user={user} post={post} disabled={'disabled'} />
same

2022-07-19 17:11 UTC, merged

2022-07-20 09:20 UTC, ZubelRuslan commented on src/containers/ReactionsContatiner.js
> +                            <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v
@Drelarusoidd Pls move svg into separate file with extension `.svg`