update player component
Drelarusoidd/React pull request #9
Opened 2022-07-21 21:47 UTC by Drelarusoidd

2022-07-21 22:17 UTC, ZubelRuslan requested changes
This is not the end  ^_^

2022-07-21 22:17 UTC, ZubelRuslan commented on src/components/PlayerComponent.js
> +        console.log('this');
Don't forget to clean your code :)

2022-07-21 22:17 UTC, ZubelRuslan commented on src/components/PlayerComponent.js
> +    }
```suggestion
    const handleChangeTrack = (rotation) = async() => {
        const response = await getPlaylist(track.playlist);
        const [urlTrack, cover, trackName] = changeTrack(rotation, response, audio.current.src);
        handleUpdatePlayer(urlTrack, cover, trackName);
    }
    const handleNextBtn = handleChangeTrack('next')
    const handlePreviousBtn = handleChangeTrack('previous')
```

2022-07-21 22:17 UTC, ZubelRuslan commented on src/components/PlayerComponent.js
>          <>
Do you really need fragment here?

2022-07-21 22:17 UTC, ZubelRuslan commented on src/services/GetPlaylist.js
> +            return JSON.stringify(response.data)
Why do you need `stringify`?

2022-07-21 22:17 UTC, ZubelRuslan commented on src/utils/changeTrack.js
> +    let trackSet = JSON.parse(data)['track_set'];
`let` ?

2022-07-21 22:17 UTC, ZubelRuslan commented on src/utils/changeTrack.js
> +    }
`Array.findIndex`

2022-07-21 22:17 UTC, ZubelRuslan commented on src/utils/changeTrack.js
> +    }
Mb in the scope only set some target index variable and then after all if/else conditions extract `url, cover, trackName` only once?

2022-07-21 22:23 UTC, Drelarusoidd commented on src/components/PlayerComponent.js
> +            audio.current.pause();
All HTMLAudioElement asynchronous.

2022-07-21 22:27 UTC, ZubelRuslan commented on src/components/PlayerComponent.js
> +            audio.current.pause();
In this case.. just FYI -- will be cool to have some error handling for errs which can happen in this operations. There is possible to use promises functionality to adjust some additional logic and error handling

2022-07-21 23:07 UTC, Drelarusoidd commented on src/components/PlayerComponent.js
> +    }
'rotation' is not defined

2022-07-22 08:08 UTC, ZubelRuslan commented on src/components/PlayerComponent.js
> +    }
> 

Forgot to add `>`

2022-07-22 08:55 UTC, ZubelRuslan requested changes

2022-07-22 09:05 UTC, ZubelRuslan approved these changes
Congrads :)

2022-07-22 09:06 UTC, merged